"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

"""


class Solution(object):
    def diff(self, s, t):  # 亦或运算，一个数亦或本身偶数次为零，奇数次为本身
        temp = s + t
        res = 0
        for char in temp:
            res ^= ord(char)
        return chr(res)

    def diffa(self, s, t):
        myDic = {}
        for char in s:
            myDic[char] = myDic.get(char, 0) + 1
        for char in t:
            if char in myDic:
                myDic[char] = myDic[char] - 1
                if myDic[char] == 0:
                    del myDic[char]
            else:
                return char


test = Solution()
print(test.diffa('abcd', 'bacde'))
